#!/bin/bash

#SBATCH -A IscrC_EXAM
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_dbg
#SBATCH --time 00:30:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0
#SBATCH --gres=gpu:4
#SBATCH --job-name=test_model
#SBATCH --out=logs/test.out
#SBATCH --err=logs/test.out

module load spack
spack load cuda@12.2.91 2>/dev/null
spack load ffmpeg@6.0 2>/dev/null

srun script/slurm/launch_test_exe $@
